#! /usr/bin/env bash

if [ $LANG = ja_JP.UTF-8 ]; then
   zenity --question --title "セキュリティに関する重要な警告" --text "あなたは管理者としてこのディレクトリを開こうとしています。これは誤操作によってシステムの破壊、重要なデータの消失、セキュリティ上の危険が発生する可能性があることを意味します。この機能はシステム全体の設定を変更する際などに使用するもので、通常のファイル操作を行うのであればこの機能は利用しないはずです。よく分からない場合は中止してください。続行しますか？" --width 480  && pkexec env DISPLAY=$DISPLAY XAUTHORITY=$XAUTHORITY nautilus $1
else
   zenity --question --title "Important security warnings" --text "You are attempting to open this directory as an administrator. This means that an erroneous operation could result in the destruction of the system, loss of important data, or a security risk. This function is used to change the settings of the entire system, etc. If you are doing normal file operations, you should not use this function. If you are unsure of what this dialog means, abort. Do you wish to continue?" --width 480  && pkexec env DISPLAY=$DISPLAY XAUTHORITY=$XAUTHORITY nautilus $1
fi


